spring.application.name=subscription_service

#KAFKA CONSUMER CONFIGURATION
spring.kafka.consumer.bootstrap-servers=kafka:9092

## Consumer Configuration
spring.kafka.consumer.group-id=subscription-service-group
#
## If starting fresh, read from the earliest available message
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
#
##Spring Kafka fallback to bypass the __TypeId__ header logic and deduce the class from the method signature
spring.kafka.consumer.properties.spring.json.value.default.type=com.aviator.subscription_service.dto.CategoryEvent

logging.level.root = info

# Force Kafka client logging into overdrive
logging.level.org.apache.kafka=INFO
logging.level.org.springframework.kafka=INFO


# Database settings with local fallbacks
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/subscription_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}

# JWT Secret with a dummy fallback for local compilation/tests
application.security.jwt.secret-key=${APPLICATION_SECURITY_JWT_SECRET_KEY:ThisIsADummySecretKeyForTestingThatIsAtLeast32CharactersLong}