spring.application.name=jwt-security


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# H2 Database Config
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin_viewer
spring.datasource.password=password

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Always initialize SQL (optional)
spring.sql.init.mode=always

# JWT Configuration
# This key must be 256-bit (at least 32 characters long)
application.security.jwt.secret-key=bWX+4c/dG5eH6jK8mN0pQ9rS2tU4vW6xY8zA6hC3dE5=
application.security.jwt.expiration=86400000
# 86400000 ms = 24 hours

# A secret password required to register as an admin
application.security.admin-secret=MySuperSecretAdminPass123!

server.port=4000

logging.level.root = info