spring.application.name=content-servive

# Global Bootstrap Servers
spring.kafka.bootstrap-servers=kafka:9092

# Producer Configuration
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer


# Database settings with local fallbacks
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/content_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Secret with a dummy fallback for local compilation/tests
application.security.jwt.secret-key=${APPLICATION_SECURITY_JWT_SECRET_KEY:ThisIsADummySecretKeyForTestingThatIsAtLeast32CharactersLong}